In [1]:
import csv
from torch.utils.data import Dataset
import torch
from sklearn.model_selection import train_test_split
import numpy as np
from bs4 import BeautifulSoup
import string
import spacy
import jsonlines
import json
import re
import torch.nn as nn
from torch.nn.utils.rnn import pad_packed_sequence,pack_padded_sequence,pad_sequence
import torch.nn.functional as F
import torch.optim as optim
import fasttext
from torch.utils.data import SubsetRandomSampler,DataLoader,Subset
from torchtext.vocab import GloVe
from tqdm import tqdm
from ray import tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler

EMBED_DIM = 300
HIDDEN_DIM = 128
CNN_DIM = 256

PATIENCE_PARAMETER = 7
VALIDATION_LOSS_COMPUTE_STEP = 1
NUM_FILTERS = 50


device_cpu = torch.device('cpu')
device_fast = torch.device('cpu')


if torch.has_mps:
    device_fast = torch.device('mps')
elif torch.has_cuda:
    device_fast = torch.device('cuda')

#torch.manual_seed(0)
#np.random.seed(0)
nlp = spacy.load('en_core_web_sm')
glove = GloVe()

c:\Users\Vivitsu329\Documents\environments\nlpenv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
torch.cuda.is_available()

False

In [3]:
def preprocess_text(text):    
    text = re.sub(r'<br /><br />',".",text)
    text = BeautifulSoup(text,'lxml').get_text().strip()
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = ' '.join(re.findall(r"[\w']+|[.,!;/\"]", text))
    
    new_text = []
    for word in text.split():
        if word == '':
            continue
        new_text.append(word)
    
    text = ' '.join(new_text)
    words = nlp(text)
    text =  " ".join([token.text for token in words if not token.is_punct or token.text=='/' or token.text=="\"" or token.text=="."]).strip()
    new_words = []
    for word in text.split(" "):
        if word == 'n\'t':
            if len(new_words) > 1:
                new_words[-1] = new_words[-1] + word
            else:
                new_words.append(word)
        else:
            new_words.append(word)
    
    text = " ".join(new_words)
    return text

In [4]:
preprocessed_dataset = []
train_dataset_labels = []
with open('./train.jsonl',encoding='utf-8') as f:
#with open('processed_dataset.jsonl',encoding='utf-8') as f:
    for line in f:
        sample = json.loads(line)
        train_dataset_labels.append(sample['label'])
        preprocessed_dataset.append(sample)
train_dataset_labels = np.array(train_dataset_labels)


In [5]:
def getWordEmbeddingforText(text,glove=glove):
    
    length = 0
    words = []
    text = text.strip()
    for word in text.split(' '):
        length+=1
        word_embedding = glove[word]
        words.append(word_embedding)

    return torch.stack(words),length

In [6]:
def review_to_embed(review,glove=glove):
    
    sentences = review.split(".")
    sentence_lengths = []
    review_embeddings = []
    num_sentences = 0
    for sentence in sentences:
        if sentence == '':
            continue
        s= sentence.strip()
        num_sentences += 1
        sentence_word_embeddings,sentence_length = getWordEmbeddingforText(s,glove)
        sentence_lengths.append(sentence_length)
        review_embeddings.append(sentence_word_embeddings)

    return torch.nn.utils.rnn.pad_sequence(review_embeddings,batch_first=True),sentence_lengths,num_sentences


In [7]:
class ReviewDataSet(Dataset):
    
    def __init__(self,reviews):
        super().__init__()
        self.reviews = reviews
        

    def __len__(self):
        return len(self.reviews)

    def __getitem__(self, index):
        return self.reviews[index]

In [8]:
processed_dataset = []

for review in preprocessed_dataset:
    embeddings, sent_length ,n_sents = review_to_embed(review['text'])
    processed_dataset.append({'review': embeddings,'sent_lengths': sent_length,'n_sent' : n_sents,'label' : review['label']})
 

In [9]:
torch.cuda.is_available()

True

In [10]:
dataset = ReviewDataSet(processed_dataset)

In [11]:
def collate_function(batch_data):
 
    
    inputs = [b['review'] for b in batch_data]
    sent_lengths = [ b['sent_lengths'] for b in batch_data ]
    n_sentences = [ b['n_sent'] for b in batch_data ]
    
    labels = torch.tensor([b['label'] for b in batch_data])

    labels = labels.unsqueeze(1)
    
    max_n_sentences = max([i.shape[0] for i in inputs] )
    max_n_words = max([i.shape[1] for i in inputs])

 
    processed_inputs = []
    for inp in inputs:

        t1 = torch.permute(inp,(2,1,0))
        t1 = torch.nn.functional.pad(t1,(0,max_n_sentences-inp.shape[0],0,max_n_words-inp.shape[1]))
        t1 = torch.permute(t1,(2,1,0))
        processed_inputs.append(t1)

    final_inp = torch.stack(processed_inputs)
    #inputs = pad_sequence(inputs,batch_first=True)
    return  {'input' : final_inp , 'sent_lengths': sent_lengths , 'n_sent' : n_sentences ,'labels' : labels }

In [12]:
train_idx,valid_idx = train_test_split(np.arange(train_dataset_labels.shape[0]), 
    test_size=0.2,
    shuffle= True,
    stratify= train_dataset_labels,
    random_state=0
)

train_sampler = SubsetRandomSampler(train_idx)
valid_sampler = SubsetRandomSampler(valid_idx)
train_dataloader = DataLoader(dataset,16,sampler=train_sampler,collate_fn=collate_function)
valid_dataloader = DataLoader(dataset,16,sampler=valid_sampler,collate_fn=collate_function)

In [13]:
import torch.nn.functional as F
class EnsembleModel(nn.Module):
    
    def __init__(self,EMBED_DIM,CNN_DIM,HIDDEN_DIM):
        super().__init__()
        self.rnn = nn.GRU(input_size = CNN_DIM,hidden_size = HIDDEN_DIM, batch_first = True)
        self.cnn = nn.Conv1d(in_channels=EMBED_DIM,out_channels=CNN_DIM,kernel_size=3)
        self.fc = nn.Linear(HIDDEN_DIM,1)


    def forward(self,inp : torch.Tensor,n_sents=None):

        ## inp  = (batch_size,max_sent_length,max_word_length,embed_dim)

        outputs = []
      
        
        for i in range(inp.shape[1]):
            current_inp = inp[:,i,:,:]
            current_inp = torch.permute(current_inp,(0,2,1))
            current_output = self.cnn(current_inp)
            current_output = F.max_pool1d(current_output,kernel_size = current_output.shape[2]).squeeze(dim=2)
            outputs.append(current_output)
        
        #print(len(outputs))
        #print(outputs[0].shape)
        lstm_in = torch.stack(outputs,dim=1)
   
        packed_input = pack_padded_sequence(lstm_in,n_sents,batch_first=True,enforce_sorted=False)
        packed_output,hidden = self.rnn(packed_input)
        output,output_lengths = pad_packed_sequence(packed_output,batch_first=True)

        hidden = torch.permute(hidden,(1,0,2))
        hidden = hidden.contiguous().view((hidden.shape[0],-1))

        out = self.fc(hidden)
        return nn.Sigmoid()(out)
        #out = self.cnn(inp)
        #return out

batch_data = next(iter(train_dataloader))
j = EnsembleModel(EMBED_DIM,CNN_DIM,HIDDEN_DIM)
j(batch_data['input'],batch_data['n_sent'])

tensor([[0.5234],
        [0.5198],
        [0.5229],
        [0.5133],
        [0.5086],
        [0.5242],
        [0.5163],
        [0.5377],
        [0.5196],
        [0.5319],
        [0.5277],
        [0.5291],
        [0.5295],
        [0.5129],
        [0.5254],
        [0.5222]], grad_fn=<SigmoidBackward0>)

In [14]:
import torch.nn.functional as F
class CNNLSTMAttention(nn.Module):
    
    def __init__(self,EMBED_DIM,CNN_DIM,HIDDEN_DIM,bidirectional_factor = 2,fc_dropout=0.3):
        super().__init__()

        bidirectional = False

        if bidirectional_factor==2:
            bidirectional = True

        self.rnn = nn.GRU(input_size = CNN_DIM,hidden_size = HIDDEN_DIM, bidirectional=bidirectional,batch_first = True)
        self.cnn = nn.Conv1d(in_channels=EMBED_DIM,out_channels=CNN_DIM,kernel_size=3)
        self.attention_layer = nn.Linear(bidirectional_factor* HIDDEN_DIM,1)
        self.fc = nn.Linear(bidirectional_factor*HIDDEN_DIM,HIDDEN_DIM)
        self.fc_dropout = nn.Dropout(fc_dropout)
        self.out_fc = nn.Linear(HIDDEN_DIM,1)
        self.batchnorm1d = nn.BatchNorm1d(CNN_DIM)

    def forward(self,inp : torch.Tensor,n_sents=None):

        ## inp  = (batch_size,max_sent_length,max_word_length,embed_dim)

        outputs = []
      
        
        for i in range(inp.shape[1]):
            current_inp = inp[:,i,:,:]
            current_inp = torch.permute(current_inp,(0,2,1))
            current_output = self.cnn(current_inp)
            current_output = F.max_pool1d(current_output,kernel_size = current_output.shape[2]).squeeze(dim=2)
            outputs.append(current_output)
        
        #print(len(outputs))
        #print(outputs[0].shape)
        lstm_in = torch.stack(outputs,dim=2)
        lstm_in = self.batchnorm1d(lstm_in)
        lstm_in = torch.permute(lstm_in,(0,2,1))

        packed_input = pack_padded_sequence(lstm_in,n_sents,batch_first=True,enforce_sorted=False)
        packed_output,hidden = self.rnn(packed_input)
        output,output_lengths = pad_packed_sequence(packed_output,batch_first=True)
        attention_logs = self.attention_layer(output).squeeze(dim=2)
        attention_score = F.softmax(attention_logs,dim=1).unsqueeze(2)

        final_out = attention_score*output

        averaged_vector = torch.sum(final_out,dim=1,keepdim=False)

        #hidden = torch.permute(hidden,(1,0,2))
        #hidden = hidden.contiguous().view((hidden.shape[0],-1))
        out = self.fc_dropout(F.leaky_relu(self.fc(averaged_vector)))
        out = self.out_fc(out)
        return nn.Sigmoid()(out)
        #out = self.cnn(inp)
        #return out


In [15]:
import os
from torch.utils.tensorboard import SummaryWriter
from datetime import  datetime

def train(model,train_dataloader,valid_dataloader,num_epochs,criterion,optimizer,
    checkpoint_name='best_model.pt',
    device_train = device_fast,use_rnn = False,log=True):

    tensorboard_name='Ensemble'
    if log == True:
        current_datetime = datetime.now().strftime("%d_%m_%Y_%H_%M_%S")
        tensorboard_name = tensorboard_name + "_" + current_datetime
        writer = SummaryWriter('runs/' + tensorboard_name)
    
    
    model = model.to(device_train)
    clip = 0
    if use_rnn:
        clip = 5

    best_validation_loss = 1000.0
    valdiation_loss_not_decreased_steps = 0
    
    model.train()
    for e in range(num_epochs):
        
        training_set_size = 0
        training_loss = 0.0
        model.train()

        for data in tqdm(train_dataloader):
            
            optimizer.zero_grad()
            input_reviews,sent_lengths,n_sents,output_labels = data['input'], data['sent_lengths'],data['n_sent'],data['labels']
            input_reviews = input_reviews.to(device_train)
            training_set_size += input_reviews.shape[0]
            output = model(input_reviews,n_sents)
            output = output.to(device_cpu)
            loss = criterion(output,output_labels.float())
            training_loss += loss.item()
            loss.backward()
            if use_rnn:
                nn.utils.clip_grad_norm_(model.parameters(),clip)
            optimizer.step()
        
        current_training_loss = training_loss
        if log==True:
            print("Epoch " + str(e) + " Average Training Loss = " +  str(current_training_loss))
            writer.add_scalars(tensorboard_name + 'Training Loss vs Epoch',{'train' : current_training_loss},e)

        
        model.eval()
        
        if valid_dataloader is None:
            continue
        
        validation_set_size  = 0 
        if e% VALIDATION_LOSS_COMPUTE_STEP==0:
            correct_count = 0
            validation_loss = 0

            for i,data in enumerate(valid_dataloader,0):
                input_reviews,sent_lengths,n_sents,output_labels = data['input'], data['sent_lengths'],data['n_sent'],data['labels']
                input_reviews = input_reviews.to(device_train)
                validation_set_size += input_reviews.shape[0]
                output = model(input_reviews,n_sents)
                output = output.to(device_cpu)
                loss = criterion(output,output_labels.float())
                validation_loss += loss.item()
                nearest_class = torch.round(output)

                correct = (nearest_class == output_labels.float()).float()
                correct_count += correct.sum()
            correct_count = int(correct_count)
            current_validation_accuracy = (correct_count/validation_set_size)*100
            current_validation_loss = (1.0* validation_loss)
            if log == True:
                print("Epoch " + str(e) + " " +  "Validation Loss = " + str(current_validation_loss) )
                print("Validation Set Accuracy = " + str((correct_count/validation_set_size)*100) )
                writer.add_scalar(tensorboard_name + ' Validation Accuracy vs Epoch ',(correct_count/validation_set_size*100),e)
                writer.add_scalars(tensorboard_name + 'Validation Loss vs Epoch',{'valid' : current_validation_loss},e)

            
            if log==True:
                if current_validation_loss < best_validation_loss:
                    valdiation_loss_not_decreased_steps = 0
                    torch.save(model.state_dict(),checkpoint_name)
                    best_validation_loss = current_validation_loss
                else:
                    valdiation_loss_not_decreased_steps +=1
        if log == True:
            if valdiation_loss_not_decreased_steps >= PATIENCE_PARAMETER:
                break

In [16]:
torch.cuda.empty_cache()

net = CNNLSTMAttention(EMBED_DIM,CNN_DIM,HIDDEN_DIM)
optimizer= optim.SGD(net.parameters(),lr=0.0054,momentum=0.9,nesterov=True)
scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, base_lr=0.0054, max_lr=0.0072,step_size_up=10000)
train(net,train_dataloader,valid_dataloader,100,nn.BCELoss(),optimizer,'first_cnn_rnn_att_adam_batch_nrom_cyclelr_bidir_0.0054.pt',device_fast,True,True)

100%|██████████| 500/500 [00:17<00:00, 28.89it/s]


Epoch 0 Average Training Loss = 304.7490390241146
Epoch 0 Validation Loss = 73.76824501156807
Validation Set Accuracy = 67.7


100%|██████████| 500/500 [00:10<00:00, 46.12it/s]


Epoch 1 Average Training Loss = 228.81198932230473
Epoch 1 Validation Loss = 61.37838926911354
Validation Set Accuracy = 74.9


100%|██████████| 500/500 [00:07<00:00, 68.15it/s]


Epoch 2 Average Training Loss = 176.9756709188223
Epoch 2 Validation Loss = 61.99554416537285
Validation Set Accuracy = 77.10000000000001


100%|██████████| 500/500 [00:07<00:00, 65.86it/s]


Epoch 3 Average Training Loss = 134.7736403569579
Epoch 3 Validation Loss = 75.53402380645275
Validation Set Accuracy = 76.3


100%|██████████| 500/500 [00:07<00:00, 64.37it/s]


Epoch 4 Average Training Loss = 102.94279106799513
Epoch 4 Validation Loss = 76.19769461452961
Validation Set Accuracy = 75.9


100%|██████████| 500/500 [00:07<00:00, 66.65it/s]


Epoch 5 Average Training Loss = 80.8386832838878
Epoch 5 Validation Loss = 92.04014156013727
Validation Set Accuracy = 76.44999999999999


100%|██████████| 500/500 [00:07<00:00, 67.66it/s]


Epoch 6 Average Training Loss = 60.15787902229931
Epoch 6 Validation Loss = 106.82008984684944
Validation Set Accuracy = 75.3


100%|██████████| 500/500 [00:07<00:00, 67.40it/s]


Epoch 7 Average Training Loss = 50.93568859464722
Epoch 7 Validation Loss = 117.82814064621925
Validation Set Accuracy = 75.14999999999999


100%|██████████| 500/500 [00:07<00:00, 66.01it/s]


Epoch 8 Average Training Loss = 48.31048094131984
Epoch 8 Validation Loss = 109.44376400113106
Validation Set Accuracy = 77.0


In [17]:
torch.cuda.empty_cache()
net = EnsembleModel(EMBED_DIM,CNN_DIM,HIDDEN_DIM)
train(net,train_dataloader,valid_dataloader,50,nn.BCELoss(),optim.Adam(net.parameters(),0.001),'cnn_rnn_dnn_adam.pt',device_fast,True,True)

  0%|          | 0/2000 [00:00<?, ?it/s]


RuntimeError: CUDA out of memory. Tried to allocate 46.00 MiB (GPU 0; 2.00 GiB total capacity; 1.64 GiB already allocated; 0 bytes free; 1.70 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

In [19]:
def test(model_name,test_data,test_lengths,test_labels):
    model = CNNLSTMAttention(EMBED_DIM,CNN_DIM,HIDDEN_DIM)
    model.load_state_dict(torch.load(model_name,map_location=device_cpu))
    model.eval()
    count = 0
    for i in range(len(test_data)):
        ans = model(test_data[i],[test_lengths[i]])
        ans = torch.round(ans)
        if ans[0][0] == test_labels[i]:
            count+=1
    
    print("Accuracy = " + str((count/len(test_data)*100)))


In [19]:
test_dataset_labels = []  
test_processed_text = []
with open("./E0334 Assignment2 Test Dataset.csv",encoding='utf-8') as csvfile:
    csvFile = csv.reader(csvfile)
    next(csvFile)
    for line in csvFile:
        processed_text = preprocess_text(line[0])
        label = 1.0 if line[1] == 'positive' else 0.0
        test_dataset_labels.append(label)
        test_processed_text.append(processed_text)

c:\Users\Vivitsu329\Documents\environments\nlpenv\lib\site-packages\bs4\__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(


In [20]:
test_word_embeddings = [] 
test_sentence_lengths = []

for i in range(len(test_processed_text)):
    
    current_embeddings,current_sent_lengths,current_n_sent = review_to_embed(test_processed_text[i]) 
    test_word_embeddings.append(current_embeddings.clone().detach().unsqueeze(0))
    test_sentence_lengths.append(current_n_sent)

In [21]:
test('./cnn_rnn_att_adam_batch_nrom_cyclelr_bidir_0.0054.pt',test_word_embeddings,test_sentence_lengths,test_dataset_labels)

Accuracy = 89.78897889788979


In [21]:

test_word_embeddings = [] 
test_sentence_lengths = []
test_dataset_labels = []  


def test_first_dataset(filename):
    
    correct_count = 0

    reviews = open(filename,'r',encoding='latin-1').readlines()
    for i in range(len(reviews)):
        r = reviews[i]
        reviews[i] = preprocess_text(r)

        current_embeddings,current_sent_lengths,current_n_sent = review_to_embed(reviews[i]) 
        if(current_embeddings.shape[0]<3):
            continue
        
        if (i<331):
            test_dataset_labels.append(1.0)
        else:
            test_dataset_labels.append(0.0)
        test_word_embeddings.append(current_embeddings.clone().detach().unsqueeze(0))
        test_sentence_lengths.append(current_n_sent)

test_first_dataset('./TestData')     

c:\Users\Vivitsu329\Documents\environments\nlpenv\lib\site-packages\bs4\__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(


In [22]:
test('./first_cnn_rnn_att_adam_batch_nrom_cyclelr_bidir_0.0054.pt',test_word_embeddings,test_sentence_lengths,test_dataset_labels)

Accuracy = 80.76923076923077


In [41]:
random_prob = 0.5*torch.ones((64,1))
true_labels = torch.bernoulli(random_prob)
print(true_labels)

tensor([[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.]])


In [42]:
import torch.optim as optim


crit = nn.BCELoss()
optimizer =optim.Adam(j.parameters(),lr = 0.01)
j.train()

Network(
  (rnn): GRU(256, 128, batch_first=True)
  (cnn): Conv1d(300, 256, kernel_size=(3,), stride=(1,))
  (fc): Linear(in_features=128, out_features=1, bias=True)
)

In [46]:
for i in range(20):

    optimizer.zero_grad()
    pred_out = j(batch_data['input'])
    loss = crit(pred_out,true_labels)
    print(loss.item())
    loss.backward()
    optimizer.step()

torch.Size([64, 77, 256])
0.6655454635620117
torch.Size([64, 77, 256])
0.6645953059196472
torch.Size([64, 77, 256])
0.66114342212677
torch.Size([64, 77, 256])
0.6593537926673889
torch.Size([64, 77, 256])
0.6578088402748108
torch.Size([64, 77, 256])
0.6835843920707703
torch.Size([64, 77, 256])
0.6554070711135864
torch.Size([64, 77, 256])
0.6443350315093994
torch.Size([64, 77, 256])
0.6433554291725159
torch.Size([64, 77, 256])
0.7229409217834473
torch.Size([64, 77, 256])
0.6723809242248535


KeyboardInterrupt: 

In [47]:
j(batch_data['input'])


torch.Size([64, 77, 256])


tensor([[0.4484],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4865],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4403],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4494],
        [0.4491],
        [0.0278],
        [0.4491],
        [0.4362],
        [0.4490],
        [0.4520],
        [0.4361],
        [0.4491],
        [0.4491],
        [0.4494],
        [0.4491],
        [0.4491],
        [0.4503],
        [0.4491],
        [0.4491],
        [0.4513],
        [0.4494],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4494],
        [0.4486],
        [0.4488],
        [0.4361],
        [0.4491],
        [0.4491],
        [0.4491],
        [0.4494],
        [0.4491],
        [0.4491],
        [0.4494],
        [0.4491],
        [0.4485],
        [0.4491],
        [0.4491],
        [0

In [64]:

pad = nn.ConstantPad2d(())
i2 = torch.randn((11,27,50))


final_out = torch.nn.utils.rnn.pad_sequence([i1,i2],batch_first=True)

RuntimeError: The size of tensor a (30) must match the size of tensor b (27) at non-singleton dimension 1

In [75]:
g = torch.randn((2,3,5))
q = torch.permute(g,(2,0,1))
g

tensor([[[ 0.2576, -1.4110, -3.0002,  1.0355,  1.4575],
         [ 1.9863, -0.6973,  0.2124,  0.2277,  0.0504],
         [-0.6911,  0.6065,  1.6002, -1.1386,  0.5833]],

        [[-0.1150, -0.1750,  0.2525,  0.1081, -0.0693],
         [ 0.3150,  0.8368, -0.0991, -0.0759, -0.4504],
         [ 0.6217, -0.9792, -1.6855,  1.4562,  0.3847]]])

In [76]:
q

tensor([[[ 0.2576,  1.9863, -0.6911],
         [-0.1150,  0.3150,  0.6217]],

        [[-1.4110, -0.6973,  0.6065],
         [-0.1750,  0.8368, -0.9792]],

        [[-3.0002,  0.2124,  1.6002],
         [ 0.2525, -0.0991, -1.6855]],

        [[ 1.0355,  0.2277, -1.1386],
         [ 0.1081, -0.0759,  1.4562]],

        [[ 1.4575,  0.0504,  0.5833],
         [-0.0693, -0.4504,  0.3847]]])

In [77]:
i = torch.nn.functional.pad(q,(0,3,0,2))

In [78]:
i = torch.permute(i,(1,2,0))